{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.serviceAccountName" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.operator.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}
rules:
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretaccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretproviders/finalizers
  verbs:
  - update
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecretproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - orbitops.dev
  resources:
  - externalsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.serviceAccountName" . | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}