{{- if .Values.webhook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook.serviceAccountName" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
  {{- with .Values.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.webhook.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "webhook.fullname" . }}
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: ["pods", "serviceaccounts"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["orbitops.dev"]
    resources: ["externalsecrets", "externalsecretaccesses"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "webhook.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook.serviceAccountName" . | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}