{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component.kscp.io: webhook
{{- end }}