---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webhook-cert-gen.fullname" . }}-create
  labels:
    {{- include "webhook-cert-gen.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "webhook-cert-gen.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "webhook-cert-gen.serviceAccountName" .  }}
      containers:
        - name: cert-gen
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - create
            - --cert-name={{ .Values.secret.certSecretKey }}
            - --key-name={{ .Values.secret.keySecretKey }}
            - --host={{ .Values.webhook.service }}.{{ .Release.Namespace }}.svc
            - --secret-name={{ .Values.secret.name }}
            - --namespace={{ .Release.Namespace }}
      restartPolicy: OnFailure